<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE colHAREMmeta [
	  
	  <!ELEMENT colHAREMmeta (DOC*)>
	  <!ATTLIST colHAREMmeta
		    versao CDATA #REQUIRED>
	  
	  <!ELEMENT DOC (VARIANTE,LISTA-TIPO_TEXTO?,FONTE)>
	  <!ATTLIST DOC
		    DOCID CDATA #REQUIRED>

	  <!-- VARIANTE: codigo que indica a variante de portugues -->
	  <!ELEMENT VARIANTE (#PCDATA)>

	  <!-- LISTA-TIPO_TEXTO: um ou mais generos que tentam categorizar o documento na coleccao HAREM -->
	  <!--               em geral, estao associados a um meio de expressao (exemplos: noticia, opiniao, didáctico) -->
	  <!--               ainda esta' sujeito a reformulacao -->
	  <!ELEMENT LISTA-TIPO_TEXTO (TIPO_TEXTO+)>
	  <!ELEMENT TIPO_TEXTO (#PCDATA)>

	  <!-- FONTE: reune diversas informacoes sobre a fonte de onde foi extraido o documento; apenas NOME e' obrigatorio -->
	  <!ELEMENT FONTE (NOME,REFERENCIA?,DOCNO?,TITULO?,AUTOR?,DATA-CRIACAO?,DATA-OBTENCAO?,SECJORNAL?,OBS?)>
	  <!-- NOME: nome da fonte; pode ser o nome de um corpus, blogue, jornal, etc. -->
	  <!ELEMENT NOME (#PCDATA)>
	  <!-- REFERENCIA: URL generico da fonte ou URL directo da entrada/documento na fonte -->
	  <!ELEMENT REFERENCIA (#PCDATA)>
	  <!-- DOCNO: codigo de identificacao do documento na fonte -->
	  <!ELEMENT DOCNO (#PCDATA)>
	  <!-- TITULO: nome do documento na fonte; pode ser o titulo de uma noticia, entrada na wikipedia, etc. -->
	  <!ELEMENT TITULO (#PCDATA)>
	  <!-- AUTOR: autor do documento -->
	  <!ELEMENT AUTOR (#PCDATA)>
	  <!-- DATA-CRIACAO: data de criacao do documento -->
	  <!ELEMENT DATA-CRIACAO (#PCDATA)>
	  <!-- DATA-OBTENCAO: data de recolha do documento -->
	  <!ELEMENT DATA-OBTENCAO (#PCDATA)>
	  <!-- SECJORNAL: classificacao do documento na fonte -->
	  <!ELEMENT SECJORNAL (#PCDATA)>
	  <!-- OBS: comentarios adicionais -->
	  <!ELEMENT OBS (#PCDATA)>
	  
	  ]>

<colHAREMmeta versao="13Nov2008">

  <DOC DOCID="cha-73943">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19940316-138</DOCNO>
      <DATA-CRIACAO>19940316</DATA-CRIACAO>
      <SECJORNAL>Cultura</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-10541">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19950430-061</DOCNO>
      <DATA-CRIACAO>19950430</DATA-CRIACAO>
      <SECJORNAL>Local</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-55664">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP940104-081</DOCNO>
      <DATA-CRIACAO>19940104</DATA-CRIACAO>
    </FONTE>
  </DOC>


  <DOC DOCID="H2-gt654">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>blogue humorístico</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>Gato Fedorento</NOME>
      <REFERENCIA>http://gatofedorento.blogspot.com/2007_02_04_archive.html#117081194450835102#117081194450835102</REFERENCIA>
      <TITULO>FAZER A FESTA, LANÇAR OS FOGUETES E APANHAR AS CANAS</TITULO>
      <AUTOR>Ricardo Araújo Pereira</AUTOR>
      <DATA-CRIACAO>20070207</DATA-CRIACAO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-2433">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19940513-023</DOCNO>
      <DATA-CRIACAO>19940513</DATA-CRIACAO>
      <SECJORNAL>Desporto</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-45967">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19941204-033</DOCNO>
      <DATA-CRIACAO>19941204</DATA-CRIACAO>
      <SECJORNAL>Mundo</SECJORNAL>
    </FONTE>
  </DOC>


  <DOC DOCID="hub-28874">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>Diário Digital</NOME>
      <REFERENCIA>http://diariodigital.sapo.pt/news.asp?id_news=311283</REFERENCIA>
      <TITULO>H5N1: Mais de 32 mil mortos se pandemia atingisse Portugal</TITULO>
      <DATA-CRIACAO>20071228</DATA-CRIACAO>
      <OBS>Agência noticiosa: Lusa</OBS>
    </FONTE>
  </DOC>


  <DOC DOCID="H2-Ren_2003_6465">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
          <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>Summ-it</NOME>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-79348">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP940109-019</DOCNO>
      <DATA-CRIACAO>19940109</DATA-CRIACAO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-18886">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19950412-059</DOCNO>
      <DATA-CRIACAO>19950412</DATA-CRIACAO>
      <SECJORNAL>Local</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="HAREM-718-00325">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>promocional</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CD Primeiro HAREM: MiniHAREM</NOME>
      <REFERENCIA>CDPrimeiroHAREM</REFERENCIA>
      <DOCNO>HAREM-718-00325</DOCNO>
    </FONTE>
  </DOC>


  <DOC DOCID="bob-14949">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>Brasil Cultura</NOME>
      <REFERENCIA>http://www.brasilcultura.com.br/conteudo.php?menu=85&amp;id=1411&amp;sub=1473</REFERENCIA>
      <TITULO>"Pequena Notável" ou a "Brazilian Bombshell"</TITULO>
      <DATA-OBTENCAO>20080104</DATA-OBTENCAO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-83761">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP940503-056</DOCNO>
      <DATA-CRIACAO>19940503</DATA-CRIACAO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-28424">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19950716-095</DOCNO>
      <DATA-CRIACAO>19950716</DATA-CRIACAO>
      <SECJORNAL>Sociedade</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-43756">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19951103-136</DOCNO>
      <DATA-CRIACAO>19951103</DATA-CRIACAO>
      <SECJORNAL>Economia</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="HAREM-649-00204">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>literário</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CD Primeiro HAREM: MiniHAREM</NOME>
      <REFERENCIA>CDPrimeiroHAREM</REFERENCIA>
      <DOCNO>HAREM-649-00204</DOCNO>
      <OBS>http://pt.wikisource.org/wiki/A_escrava_Isaura/X</OBS>
    </FONTE>
  </DOC>


  <DOC DOCID="hub-83020">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>Público</NOME>
      <REFERENCIA>http://ultimahora.publico.clix.pt/noticia.aspx?id=1315090&amp;idCanal=57</REFERENCIA>
      <TITULO>Espanha aumenta salário mínimo para 600 euros</TITULO>
      <DATA-CRIACAO>20071228</DATA-CRIACAO>
      <OBS>Agência noticiosa: AFP</OBS>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-91193">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19950812-175</DOCNO>
      <DATA-CRIACAO>19950812</DATA-CRIACAO>
      <SECJORNAL>Nacional/Portugal</SECJORNAL>
    </FONTE>
  </DOC>


  <DOC DOCID="hub-16632">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>blogue humorístico</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>Gato Fedorento</NOME>
      <REFERENCIA>http://gatofedorento.blogspot.com/2006_08_13_archive.html#115560419151423370#115560419151423370</REFERENCIA>
      <TITULO>A MINHOCA E A MAÇÃ</TITULO>
      <AUTOR>Ricardo Araújo Pereira</AUTOR>
      <DATA-CRIACAO>20060815</DATA-CRIACAO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-47488">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19950619-064</DOCNO>
      <DATA-CRIACAO>19950619</DATA-CRIACAO>
      <SECJORNAL>Local</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-16456">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19950228-050</DOCNO>
      <DATA-CRIACAO>19950228</DATA-CRIACAO>
      <SECJORNAL>Mundo</SECJORNAL>
    </FONTE>
  </DOC>


  <DOC DOCID="hub-94570">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>didáctico</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>Wikipédia</NOME>
      <REFERENCIA>http://pt.wikipedia.org/wiki/Lobotomia</REFERENCIA>
      <TITULO>Lobotomia</TITULO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-70524">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP940102-150</DOCNO>
      <DATA-CRIACAO>19940102</DATA-CRIACAO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-49276">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP951226-052</DOCNO>
      <DATA-CRIACAO>19951226</DATA-CRIACAO>
      <SECJORNAL>COTIDIANO</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-92285">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19940720-044</DOCNO>
      <DATA-CRIACAO>19940720</DATA-CRIACAO>
      <SECJORNAL>Mundo</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-55494">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19950606-062</DOCNO>
      <DATA-CRIACAO>19950606</DATA-CRIACAO>
      <SECJORNAL>Mundo</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-46329">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19951004-059</DOCNO>
      <DATA-CRIACAO>19951004</DATA-CRIACAO>
      <SECJORNAL>Local</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-80116">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19950202-154</DOCNO>
      <DATA-CRIACAO>19950202</DATA-CRIACAO>
      <SECJORNAL>Sociedade</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-13143">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19940124-087</DOCNO>
      <DATA-CRIACAO>19940124</DATA-CRIACAO>
      <SECJORNAL>Mundo</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-82306">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19940504-053</DOCNO>
      <DATA-CRIACAO>19940504</DATA-CRIACAO>
      <SECJORNAL>Mundo</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-83980">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19950123-056</DOCNO>
      <DATA-CRIACAO>19950123</DATA-CRIACAO>
      <SECJORNAL>Local</SECJORNAL>
    </FONTE>
  </DOC>


  <DOC DOCID="cver">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>opinião</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>EXPRESSO</NOME>
      <REFERENCIA>http://aeiou.expresso.pt/gen.pl?p=stories&amp;op=view&amp;fokey=ex.stories/201677</REFERENCIA>
      <TITULO>Uma nação de pedintes</TITULO>
      <AUTOR>Clara Ferreira Alves</AUTOR>
      <DATA-CRIACAO>20071229</DATA-CRIACAO>
      <DATA-OBTENCAO>20071229</DATA-OBTENCAO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-37008">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19950414-050</DOCNO>
      <DATA-CRIACAO>19950414</DATA-CRIACAO>
      <SECJORNAL>Mundo</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-77767">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19951007-056</DOCNO>
      <DATA-CRIACAO>19951007</DATA-CRIACAO>
      <SECJORNAL>Local</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-11954">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP940108-124</DOCNO>
      <DATA-CRIACAO>19940108</DATA-CRIACAO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-80612">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19941207-062</DOCNO>
      <DATA-CRIACAO>19941207</DATA-CRIACAO>
      <SECJORNAL>Mundo</SECJORNAL>
    </FONTE>
  </DOC>


  <DOC DOCID="ric-78733">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>blogue pessoal</TIPO_TEXTO>
      <TIPO_TEXTO>didáctico</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>OVERMUNDO</NOME>
      <REFERENCIA>http://www.overmundo.com.br/agenda/cavalo-marinho-boi-pintado-o-dia-de-reis-e-a-lei-rouanet</REFERENCIA>
      <TITULO>Cavalo-marinho Boi PIntado, o dia de Reis e a Lei Rouanet</TITULO>
      <AUTOR>Rosa Campello</AUTOR>
      <DATA-CRIACAO>20072131</DATA-CRIACAO>
      <DATA-OBTENCAO>20080102</DATA-OBTENCAO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-54533">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19950131-080</DOCNO>
      <DATA-CRIACAO>19950131</DATA-CRIACAO>
      <SECJORNAL>Diversos</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-76935">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP940208-142</DOCNO>
      <DATA-CRIACAO>19940208</DATA-CRIACAO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-58414">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19950905-074</DOCNO>
      <DATA-CRIACAO>19950905</DATA-CRIACAO>
      <SECJORNAL>Local</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-87801">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP950207-091</DOCNO>
      <DATA-CRIACAO>19950207</DATA-CRIACAO>
      <SECJORNAL>COTIDIANO</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-34534">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19940325-081</DOCNO>
      <DATA-CRIACAO>19940325</DATA-CRIACAO>
      <SECJORNAL>Local</SECJORNAL>
    </FONTE>
  </DOC>


  <DOC DOCID="hub-30518">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>didáctico</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>Wikipédia</NOME>
      <REFERENCIA>http://pt.wikipedia.org/wiki/Rfid</REFERENCIA>
      <TITULO>RFID</TITULO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-73845">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP940103-111</DOCNO>
      <DATA-CRIACAO>19940103</DATA-CRIACAO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-21705">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19950308-045</DOCNO>
      <DATA-CRIACAO>19950308</DATA-CRIACAO>
      <SECJORNAL>Cien_Tecn_Educ</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-82225">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP940210-121</DOCNO>
      <DATA-CRIACAO>19940210</DATA-CRIACAO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-87746">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP940504-061</DOCNO>
      <DATA-CRIACAO>19940504</DATA-CRIACAO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-40584">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP950114-061</DOCNO>
      <DATA-CRIACAO>19950114</DATA-CRIACAO>
      <SECJORNAL>COTIDIANO</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-29559">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP940504-059</DOCNO>
      <DATA-CRIACAO>19940504</DATA-CRIACAO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-8522">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19940926-090</DOCNO>
      <DATA-CRIACAO>19940926</DATA-CRIACAO>
      <SECJORNAL>Cultura</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-87348">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19940426-157</DOCNO>
      <DATA-CRIACAO>19940426</DATA-CRIACAO>
      <SECJORNAL>Mundo</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-44009">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP940302-112</DOCNO>
      <DATA-CRIACAO>19940302</DATA-CRIACAO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-31496">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP940107-137</DOCNO>
      <DATA-CRIACAO>19940107</DATA-CRIACAO>
    </FONTE>
  </DOC>


  <DOC DOCID="H2-bbb">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>blogue humorístico</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>Gato Fedorento</NOME>
      <REFERENCIA>http://gatofedorento.blogspot.com/2007_07_01_archive.html#317235169139692284#317235169139692284</REFERENCIA>
      <TITULO>HEIDEGGER e o 4-4-2</TITULO>
      <AUTOR>Miguel Góis</AUTOR>
      <DATA-CRIACAO>20070706</DATA-CRIACAO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-8032">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP940312-115</DOCNO>
      <DATA-CRIACAO>19940312</DATA-CRIACAO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-16371">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP951130-118</DOCNO>
      <DATA-CRIACAO>19951130</DATA-CRIACAO>
      <SECJORNAL>COTIDIANO</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-78164">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19950201-069</DOCNO>
      <DATA-CRIACAO>19950201</DATA-CRIACAO>
      <SECJORNAL>Local</SECJORNAL>
    </FONTE>
  </DOC>


  <DOC DOCID="hub-68694">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>didáctico</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>Wikipédia</NOME>
      <REFERENCIA>http://pt.wikipedia.org/wiki/Multibanco</REFERENCIA>
      <TITULO>Multibanco</TITULO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-84029">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP940314-083</DOCNO>
      <DATA-CRIACAO>19940314</DATA-CRIACAO>
    </FONTE>
  </DOC>


  <DOC DOCID="aa77651">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>Portal do Governo</NOME>
      <REFERENCIA>http://www.portugal.gov.pt/Portal/PT/Governos/Governos_Constitucionais/GC17/Ministerios/MDN/Comunicacao/Notas_de_Imprensa/20071229_MDN_Com_Afeganist%C3%A3o.htm</REFERENCIA>
      <TITULO>Ministro da Defesa visita tropas portuguesas no Afeganistão</TITULO>
      <DATA-CRIACAO>20071228</DATA-CRIACAO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-34681">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19940105-086</DOCNO>
      <DATA-CRIACAO>19940105</DATA-CRIACAO>
      <SECJORNAL>Sociedade</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-3899">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19950712-052</DOCNO>
      <DATA-CRIACAO>19950712</DATA-CRIACAO>
      <SECJORNAL>Mundo</SECJORNAL>
    </FONTE>
  </DOC>


  <DOC DOCID="aa33715">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>blogue jornalístico</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>Economista poeta</NOME>
      <REFERENCIA>http://aeiou.expresso.pt/gen.pl?sid=ex.sections/23463</REFERENCIA>
      <DATA-CRIACAO>20071227</DATA-CRIACAO>
      <OBS>blogue do Expresso</OBS>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-34133">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP940108-081</DOCNO>
      <DATA-CRIACAO>19940108</DATA-CRIACAO>
    </FONTE>
  </DOC>


  <DOC DOCID="hub-60382">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>Record</NOME>
      <REFERENCIA>http://www.record.pt/noticia.asp?id=757630&amp;idCanal=2438</REFERENCIA>
      <TITULO>Mundial: Rui Cordeiro e Lobos arrepiam franceses</TITULO>
      <AUTOR>Sérgio Lopes</AUTOR>
      <DATA-CRIACAO>20070912</DATA-CRIACAO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-89938">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19941231-150</DOCNO>
      <DATA-CRIACAO>19941231</DATA-CRIACAO>
      <SECJORNAL>Desporto</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-11280">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19950620-078</DOCNO>
      <DATA-CRIACAO>19950620</DATA-CRIACAO>
      <SECJORNAL>Local</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="wpt-10034934164544455">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>WPT05</NOME>
      <REFERENCIA>http://www.acoeug.com/phpbb/viewtopic.php?&amp;view=next&amp;t=15</REFERENCIA>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-71095">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP950414-079</DOCNO>
      <DATA-CRIACAO>19950414</DATA-CRIACAO>
      <SECJORNAL>COTIDIANO</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-99785">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19940627-052</DOCNO>
      <DATA-CRIACAO>19940627</DATA-CRIACAO>
      <SECJORNAL>Mundo</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-48768">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP940102-194</DOCNO>
      <DATA-CRIACAO>19940102</DATA-CRIACAO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-8177">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP940116-061</DOCNO>
      <DATA-CRIACAO>19940116</DATA-CRIACAO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-70560">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19940513-084</DOCNO>
      <DATA-CRIACAO>19940513</DATA-CRIACAO>
      <SECJORNAL>Diversos</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-77090">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19940313-091</DOCNO>
      <DATA-CRIACAO>19940313</DATA-CRIACAO>
      <SECJORNAL>Diversos</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-83021">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19940609-051</DOCNO>
      <DATA-CRIACAO>19940609</DATA-CRIACAO>
      <SECJORNAL>Mundo</SECJORNAL>
    </FONTE>
  </DOC>


  <DOC DOCID="hub-57257">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>Diário Digital</NOME>
      <REFERENCIA>http://diariodigital.sapo.pt/news.asp?section_id=14&amp;id_news=311069</REFERENCIA>
      <TITULO>«Call girl» estreia hoje em 40 salas de cinema</TITULO>
      <DATA-CRIACAO>20071227</DATA-CRIACAO>
      <OBS>Agência noticiosa: Lusa</OBS>
    </FONTE>
  </DOC>


  <DOC DOCID="relkj7666">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>didáctico</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>Museu Histórico Nacional</NOME>
      <REFERENCIA>http://www.museuhistoriconacional.com.br</REFERENCIA>
      <DATA-OBTENCAO>20080104</DATA-OBTENCAO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-81393">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19940806-015</DOCNO>
      <DATA-CRIACAO>19940806</DATA-CRIACAO>
      <SECJORNAL>Desporto</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-30287">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19941016-062</DOCNO>
      <DATA-CRIACAO>19941016</DATA-CRIACAO>
      <SECJORNAL>Local</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-73181">
    <VARIANTE>pt_PT</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>PUBLICO-19940507-131</DOCNO>
      <DATA-CRIACAO>19940507</DATA-CRIACAO>
      <SECJORNAL>Mundo</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-46556">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP940729-050</DOCNO>
      <DATA-CRIACAO>19940729</DATA-CRIACAO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-93076">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP950430-115</DOCNO>
      <DATA-CRIACAO>19950430</DATA-CRIACAO>
      <SECJORNAL>ESPORTE</SECJORNAL>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-23475">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP940310-133</DOCNO>
      <DATA-CRIACAO>19940310</DATA-CRIACAO>
    </FONTE>
  </DOC>

  <DOC DOCID="cha-49273">
    <VARIANTE>pt_BR</VARIANTE>
    <LISTA-TIPO_TEXTO>
      <TIPO_TEXTO>notícia</TIPO_TEXTO>
    </LISTA-TIPO_TEXTO>
    <FONTE>
      <NOME>CHAVE</NOME>
      <DOCNO>FSP940107-045</DOCNO>